### ISSUE TITLE
query _list returns Error

### ISSUE THREAD

**Issue by holymoly** [couchapp/couchapp#234] opened 2016-05-07 18:02 UTC
Hi,

When i use the following function 
```
$.couch.db("db").list("app/listfunction", "viewfunction", {
    success: function(data) {
        console.log(data);
    },
    error: function(status) {
        console.log(status);
    },
});
</script>
```
I get the error
```
jquery.js:8434 GET http://1.2.3.4:5984/db/_design/app/_list/listfunction/viewfunction 406 (Not Acceptable)send @ jquery.js:8434jQuery.extend.ajax @ jquery.js:7986ajax @ jquery.couch.js:984list @ jquery.couch.js:818(anonymous function) @ index.html:61
jquery.couch.js:1016 Uncaught An error occurred accessing the list: Content-Type application/json not supported, try one of: text/html; charset=utf-8
```
The _list functions generates a HTML Table. If I open http://1.2.3.4:5984/db/_design/app/_list/listfunction/viewfunction directly I can see the Table. Just when my page uses the function from above I get the error.

**Comment by iblis17** [comment] 2016-05-08 08:17
Hi @holymoly 
Currently no idea....
I guess we need test following situations:

1. change `dataType` of jQuery ajax option (this indicate how jQuery parse the response data
2. change `Accept` header to `text/plain`
3. change both of `Accept` header and `dataType`

First, it seems that we need the correct the position of args.
```javascript
$.couch.db("db").list("app/listfunction", "viewfunction", null, {
    success: ...,
    error: ...,
});
```

#### change `dataType` option
Please test this:
```javascript
$.couch.db("db").list("app/listfunction", "viewfunction", null, {
    dataType: "text",
    success: ...,
    error: ...,
});
```

#### change `Accept` header
Rmove the `dataType` option in our function call.

Then, please try this patch ( not test yet ), 
  apply it to `${PREFIX}/share/couchdb/www/script/jquery.couch.js`
```diff
diff --git a/jquery.couch.js b/jquery.couch.js
index 561d6f4..5344909 100644
--- a/jquery.couch.js
+++ b/jquery.couch.js
@@ -837,8 +837,12 @@
               data: data,
               url: this.uri + '_design/' + list[0] +
                    '/_list/' + list[1] + '/' + view + encodeOptions(options)
-              },
-              ajaxOptions, 'An error occurred accessing the list'
+              },           /* `obj` in `ajax` declaration */
+              ajaxOptions, /* `options` in `ajax` declaration */
+              'An error occurred accessing the list', /* `errorMessage` */
+              {
+                headers: {'Accept': 'text/plain'},
+              }          /* `ajaxOptions` in `ajax` declaration */
           );
         },
```

Which one works for you?

**Comment by holymoly** [comment] 2016-05-08 08:57
So I started testing. When I passed the null the error handler was executed.
```
jquery.js:8434 GET http://45.62.255.9:5984/geofency/_design/helloworld/_list/geo-table/details 406 (Not Acceptable)send @ jquery.js:8434jQuery.extend.ajax @ jquery.js:7986ajax @ jquery.couch.js:984list @ jquery.couch.js:818(anonymous function) @ index.html:54
index.html:59 error406
```

Before I move on I just have a question about my list function.
```
function(head, req) {
  provides('html', function(){
    var text;
    text = "<table class='table'><thead><tr><th>Date</th><th>Name</th><th>Entry</th><th>Address</th><th>Latitude</th><th>Longitude</th><th>device</th><th>Radius</th></tr></thead>\n";
    text += "<tbody>\n";

    while (row = getRow()) {
      text += "<tr>\n";

      text += "<td>" + row.key + "</td>\n";
      text += "<td>" + row.value.place + "</td>\n";
      text += "<td>" + row.value.entry + "</td>\n";
      text += "<td>" + row.value.address + "</td>\n";
      text += "<td>" + row.value.geo.latitude + "</td>\n";
      text += "<td>" + row.value.geo.longitude + "</td>\n";
      text += "<td>" + row.value.device + "</td>\n";
      text += "<td>" + row.value.radius + "</td>\n";

      text += "</tr>\n";
    }
    text += "</tbody></table>\n";

    return text;
  });
}
```
when I use this one I get the error as described above.

When I change it to (no provide):
```
function(head, req) {
    var text;
    text = "<table class='table'><thead><tr><th>Date</th><th>Name</th><th>Entry</th><th>Address</th><th>Latitude</th><th>Longitude</th><th>device</th><th>Radius</th></tr></thead>\n";
    text += "<tbody>\n";

    while (row = getRow()) {
      text += "<tr>\n";

      text += "<td>" + row.key + "</td>\n";
      text += "<td>" + row.value.place + "</td>\n";
      text += "<td>" + row.value.entry + "</td>\n";
      text += "<td>" + row.value.address + "</td>\n";
      text += "<td>" + row.value.geo.latitude + "</td>\n";
      text += "<td>" + row.value.geo.longitude + "</td>\n";
      text += "<td>" + row.value.device + "</td>\n";
      text += "<td>" + row.value.radius + "</td>\n";

      text += "</tr>\n";
    }
    text += "</tbody></table>\n";

    return text;

}
```
I get the error:
```
index.html:60 error200
```
So the error handler gets executed but tells me it is OK.
Is there maybe something I missed in my list function? I just want to make sure its ok before I do the rest of the Tests.

**Comment by holymoly** [comment] 2016-05-08 09:30
I did the other tests as well. I changed the dataType and the Accept header. The errors are still the same as in the previous message.

**Comment by iblis17** [comment] 2016-05-08 09:33
Ha..ha.. :sob:
Maybe your `list` function make a landmine in `jquery.couch.js` blow up!
Your `list` is correct.
ref: https://github.com/apache/couchdb-jquery-couch/blob/master/jquery.couch.js#L1012-L1020

Err... let's patch it.

**Comment by iblis17** [comment] 2016-05-08 09:57
Is the error msg of second version `list` (with `provide`) something about json parsing error?

**Comment by iblis17** [comment] 2016-05-08 10:01
Hope this rough patch help:
```diff
diff --git a/jquery.couch.js b/jquery.couch.js
index 561d6f4..d5b04c0 100644
--- a/jquery.couch.js
+++ b/jquery.couch.js
@@ -1010,7 +1014,12 @@
       complete: function(req) {
         var reqDuration = (new Date()).getTime() - timeStart;
         try {
-          var resp = $.parseJSON(req.responseText);
+          if (req.getResponseHeader('Content-Type') === 'application/json') {
+            var resp = $.parseJSON(req.responseText);
+          }
+          else {
+            var resp = req.responseText;
+          }
         } catch(e) {
           if (options.error) {
             options.error(req.status, req, e);
```

**Comment by holymoly** [comment] 2016-05-08 10:04
I only get a json error if i remove the null from
```
$.couch.db("db").list("app/listfunction", "viewfunction", null, {
    success: ...,
    error: ...,
});
```

So it was assuming that the response is always json? Will try the patch now

**Comment by holymoly** [comment] 2016-05-08 10:19
So its working with the last patch and 
```
$.couch.db("db").list("app/listfunction", "viewfunction", null, {
    dataType: "text",
    success: ...,
    error: ...,
});
```
(null and datatype) 
and
```
function(head, req) {
  provides('text', function(){
    var text;
    text = "<table class='table'><thead><tr><th>Date</th><th>Name</th><th>Entry</th><th>Address</th><th>Latitude</th><th>Longitude</th><th>device</th><th>Radius</th></tr></thead>\n";
    text += "<tbody>\n";

    while (row = getRow()) {
      text += "<tr>\n";

      text += "<td>" + row.key + "</td>\n";
      text += "<td>" + row.value.place + "</td>\n";
      text += "<td>" + row.value.entry + "</td>\n";
      text += "<td>" + row.value.address + "</td>\n";
      text += "<td>" + row.value.geo.latitude + "</td>\n";
      text += "<td>" + row.value.geo.longitude + "</td>\n";
      text += "<td>" + row.value.device + "</td>\n";
      text += "<td>" + row.value.radius + "</td>\n";

      text += "</tr>\n";
    }
    text += "</tbody></table>\n";

    return text;
  });
}
```
(provides('text', function()..)
It not working with datatype html. But i use text for now.
Thanks for the help!!!!

**Comment by iblis17** [comment] 2016-05-08 10:29
oh, the available value of dataType can be `xml, json, script, or html` (ref http://api.jquery.com/jQuery.ajax

Just set the valude according to `provides`.

**Comment by holymoly** [comment] 2016-05-08 10:36
I changed the value. With html i get the error 
```
Failed to load resource: the server responded with a status of 406 (Not Acceptable)
index.html:63 error406
```
Could be auth stuff...

**Comment by iblis17** [comment] 2016-05-08 10:40
I am curious about the HTTP response headers.
Would you just point brower to your list function and show response header via brower debug console?

**Comment by holymoly** [comment] 2016-05-08 11:04
I configured my couchdb to ask for passwords on all the sites. So when i open the url of the list function in the browser, a pop up asking me for user and pass. if I abort the header is: 
```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="administrator"
Server: CouchDB/1.6.1 (Erlang OTP/18)
Date: Sun, 08 May 2016 10:54:03 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 61
Cache-Control: must-revalidate
```
If i log in i get:
```
HTTP/1.1 304 Not Modified
Server: CouchDB/1.6.1 (Erlang OTP/18)
ETag: "6KU05Z1VZ95CO5NHF8EKK8WOW"
Date: Sun, 08 May 2016 10:55:49 GMT
Content-Length: 0
```
Hope that helps, not a pro on these things.

If I use the url in curl i have to put in user and password like:
http://user:pass@1.2.3.4:5984/db/_design/app/_list/listfunction/viewfunction

Is this the same as when i write?
```
$.couch.db("db").list("app/listfunction", "viewfunction", null, {
    username: "user",
    passworde: "awesomesecret",
    dataType: "text",
    success: ...,
    error: ...,
});
```

**Comment by iblis17** [comment] 2016-05-08 11:59
About the HTTP 406 status code, it's not the auth related issue:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
> 10.4.7 406 Not Acceptable

> The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request. 

This is caused by
 - client `Accept` header
 - server response `Content-Type`

mismatch.

----
add `username` and `password` is fine

**Comment by iblis17** [comment] 2016-05-08 12:28
I will try to reproduce error 406 later…  i am on the bus :sob:

**Comment by holymoly** [comment] 2016-05-08 14:50
If it helps, I just got the request and response Header wich leads to the 406.

Server response Content-Type is set by the provide function and client accept header by dataType, both to 'html'.

request:
```
GET /db/_design/app/_list/listfunction/viewfunction HTTP/1.1
Host: 1.2.3.4:5984
Connection: keep-alive
Authorization: Basic aelseW1vbHk6Z3RzdHNkaDFBQA==
Accept: text/plain
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36
Content-Type: application/json
Referer: http://1.2.3.4:5984/db/_design/app/index.html
Accept-Encoding: gzip, deflate, sdch
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: AuthSession=aelseW1vbHk6NTcyRTIyREQ6BVw-VJ62d7JyLqjPBkrcEhAEzmc
If-None-Match: "1L0MZO5GW8MGVXW4HKT6DTK3L"﻿
```
response:
```
HTTP/1.1 406 Not Acceptable
Server: CouchDB/1.6.1 (Erlang OTP/18)
Date: Sun, 08 May 2016 14:33:43 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 114
Cache-Control: must-revalidate
```

**Comment by iblis17** [comment] 2016-05-08 14:54
:-o please remove the header `Authorization` ...

**Comment by holymoly** [comment] 2016-05-08 14:57
you mean i shouldn't have posted that? Its not the original one, I changed those manually before posting.

**Comment by iblis17** [comment] 2016-05-08 15:00
FYI: https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side

**Comment by iblis17** [comment] 2016-05-08 15:05
No idea about why the `Accept` set to `plain/text` ...

Are you using this patch or not?
```diff
diff --git a/jquery.couch.js b/jquery.couch.js
index 561d6f4..5344909 100644
--- a/jquery.couch.js
+++ b/jquery.couch.js
@@ -837,8 +837,12 @@
               data: data,
               url: this.uri + '_design/' + list[0] +
                    '/_list/' + list[1] + '/' + view + encodeOptions(options)
-              },
-              ajaxOptions, 'An error occurred accessing the list'
+              },           /* `obj` in `ajax` declaration */
+              ajaxOptions, /* `options` in `ajax` declaration */
+              'An error occurred accessing the list', /* `errorMessage` */
+              {
+                headers: {'Accept': 'text/plain'},
+              }          /* `ajaxOptions` in `ajax` declaration */
           );
         },
```

**Comment by holymoly** [comment] 2016-05-08 15:09
Yes, Its still in.
```
return ajax({
    type: type,
    data: data,
    url: this.uri + '_design/' + list[0] +
         '/_list/' + list[1] + '/' + view + encodeOptions(options)
    },           /* `obj` in `ajax` declaration */
    ajaxOptions, /* `options` in `ajax` declaration */
    'An error occurred accessing the list', /* `errorMessage` */
    {
      headers: {'Accept': 'text/plain'},
    }          /* `ajaxOptions` in `ajax` declaration */
);
```

**Comment by iblis17** [comment] 2016-05-08 15:10
We got it!

**Comment by holymoly** [comment] 2016-05-08 15:12
? Im not getting it :sob:

**Comment by iblis17** [comment] 2016-05-08 15:20
In order to sort out which patche is useful..

Let's test `dataType` and `Accept` indiviually. We will set `Accept` and `provide` to `html`.

First, make sure this patch applied
```diff
diff --git a/jquery.couch.js b/jquery.couch.js
index 561d6f4..d5b04c0 100644
--- a/jquery.couch.js
+++ b/jquery.couch.js
@@ -1010,7 +1014,12 @@
       complete: function(req) {
         var reqDuration = (new Date()).getTime() - timeStart;
         try {
-          var resp = $.parseJSON(req.responseText);
+          if (req.getResponseHeader('Content-Type') === 'application/json') {
+            var resp = $.parseJSON(req.responseText);
+          }
+          else {
+            var resp = req.responseText;
+          }
         } catch(e) {
           if (options.error) {
             options.error(req.status, req, e);
```

Second, set the `provides` in list function to `html`. 

Next, test each folloing case

1. change dataType of jQuery ajax option (this indicate how jQuery parse the response data
2. change Accept header to text/plain
3. change both of Accept header and dataType

Note that the  `Accept` patch should be
```diff
diff --git a/jquery.couch.js b/jquery.couch.js
index 561d6f4..5344909 100644
--- a/jquery.couch.js
+++ b/jquery.couch.js
@@ -837,8 +837,12 @@
               data: data,
               url: this.uri + '_design/' + list[0] +
                    '/_list/' + list[1] + '/' + view + encodeOptions(options)
-              },
-              ajaxOptions, 'An error occurred accessing the list'
+              },           /* `obj` in `ajax` declaration */
+              ajaxOptions, /* `options` in `ajax` declaration */
+              'An error occurred accessing the list', /* `errorMessage` */
+              {
+                headers: {'Accept': 'text/html'},   // <-------------------------- here is the key
+              }          /* `ajaxOptions` in `ajax` declaration */
           );
         },
```

**Comment by holymoly** [comment] 2016-05-08 15:37
So, first and second patch are applied. 
1. The provide and Accept header are set to html. Also the dataType is set to html.
  -> Works like a charm for html.
2. changed Accept header to text/plain
  -> throws the 406 error
3. changed both of Accept header and dataType
a) if i change Accept header and dataType to the type of the provide function
  -> works like a charm for html an text
b)if i change Accept header and dataType to the type to another value then the provide function
  -> -> throws the 406 error

**Comment by iblis17** [comment] 2016-05-08 15:46
Fine!
> 1. The provide and Accept header are set to html. Also the dataType is set to html.
> -> Works like a charm for html.
> 2. changed Accept header to text/plain
> -> throws the 406 error
Base on those result, I just want to confirm that `dataType` is useless.
One more experiment: "remove `dataType` and set `Accept header to `text/html`".

**Comment by holymoly** [comment] 2016-05-08 15:55
I can confirm that. Datatype is not needed. Just the Accept header has to match the provide function.

**Comment by iblis17** [comment] 2016-05-08 15:57
:tada: :tada: :fireworks: 
I will refine those patches and send them to upstream!

**Comment by holymoly** [comment] 2016-05-08 15:58
Cool, thanks for your time!!! 👍

**Comment by iblis17** [comment] 2016-06-02 03:18
Our patch has been merged to upstream!
apache/couchdb-jquery-couch#5

:tada:

**Closed by iblis17** 2016-06-02 03:18 UTC
